---
role_name_check: 1

dependency:
  name: galaxy
  options:
    ignore-errors: true

provisioner:
  name: ansible

driver:
  name: docker

platforms:
  - name: debian-12
    image: fernandobohrer/docker-ansible-debian-12:latest
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
