---
role_name_check: 1

dependency:
  name: galaxy
  options:
    ignore-errors: true

provisioner:
  name: ansible

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: debian-12
    box: debian/bookworm64
    cpus: 2
    memory: 2048
